### ISSUE TITLE
Cannot open TUN/TAP error after docker upgrade

### ISSUE THREAD

**Issue by nnachtegael** [rvben/rpi-openvpn#1]
after upgrade to Docker version 27.4.0, build bde2b89 I got the following error

ERROR: Cannot open TUN/TAP dev /dev/net/tun: Operation not permitted (errno=1) and the container did not work anymore.

adding **--privileged** to starting container command solved the problem

docker run -v $OVPN_DATA:/etc/openvpn -d -p 1194:1194/udp **--privileged** --cap-add=NET_ADMIN rvben/rpi-openvpn

**Comment by rvben** [comment]
Hi @nnachtegael,

Thanks for reporting this issue, and thanks for sharing your solution.
The `--privileged` flag gives a lot of (unused) permissions to the container. What I found is that adding `--device=/dev/net/tun` to the command give the container enough privileges, but not more. If you can verify that, that would be great as I don't have a setup at the moment to verify this.

Full command would be:
```
docker run -v $OVPN_DATA:/etc/openvpn -d -p 1194:1194/udp --device=/dev/net/tun --cap-add=NET_ADMIN rvben/rpi-openvpn
```

Kind regards,

Ruben

**Comment by nnachtegael** [comment]
Hi Ruben
It's working for me

**Comment by rvben** [comment]
Thanks @nnachtegael! I've updated the documentation in #977dd5e and will close the issue.
